# Generated by Django 5.1.4 on 2026-08-16 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='departments',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.department'),
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user', 'skill', 'is_approved')},
        ),
        migrations.DeleteModel(
            name='DepartmentUser',
        ),
    ]
